apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-staging
  namespace: stage
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    persistentvolumeclaims: "10"
    requests.storage: "25Gi"
